### ISSUE TITLE
Two typos in extensions/XInput.d

### ISSUE THREAD

**Issue by tychonievich** [nomad-software/x11#14]
XInput.d line 34 is
```auto FindTypeAndClass(A,B,C,D,E)(ref A d, ref B type, ref C _class, ref D classid, ref E offset){```
but `FindTypeAndClass` is invoked with `enum` values for its last to arguments on lines 46–136 and `enum`s are evaluated as values at compile time and cannot be passed by reference; it ought to be
```auto FindTypeAndClass(A,B,C,D,E)(ref A d, ref B type, ref C _class, D classid, E offset){```
instead.

XInput.d line 713 is
```alias XValuatorInfoPtr = XAxisInfo*;```
It ought to be
```alias XValuatorInfoPtr = XValuatorInfo*;```
instead.

**Comment by nomad-software** [comment]
Fixed: https://github.com/nomad-software/x11/commit/3ec5846c24722532e5a95e92fe4d0954cf818ec6
