### ISSUE TITLE
Typo in XInput.d

### ISSUE THREAD

**Issue by tychonievich** [nomad-software/x11#15]
Lines 40 and 736 do not agree, differing in trailing underscore.  Either 40 should use `input_class_` or 736 should use `input_class`

**Comment by nomad-software** [comment]
Thanks for the report fixed in the latest release.
https://github.com/nomad-software/x11/releases/tag/v1.0.11
http://code.dlang.org/my_packages/x11

If you spot anymore I urge you to raise a PR. :)
