### ISSUE TITLE
merge back with deimos

### ISSUE THREAD

**Issue by wilzbach** [nomad-software/x11#17]
> I've purposely not forked because the overall structure has been changed to suit the dub build tool. Hopefully this is a temporary measure until the entirety of Deimos is moved to dub.

Afaict deimos now uses dub - so how about using that and merging your changes back?

**Comment by nomad-software** [comment]
There have been too many bug fixes in this repo to merge back.

**Comment by nomad-software** [comment]
Actually, I'll think about it.

**Comment by MartinNowak** [comment]
I'd say the http://github.com/D-Programming-Deimos organization is more or less dead as it obviously doesn't scale to ask a central instance to add new packages, merge random PRs, and tag releases.
Long live Deimos the idea ([DIP12](https://wiki.dlang.org/DIP12)) but as free and decentral dub packages ;).

**Comment by nomad-software** [comment]
Yeah I agree with Martin. It's doing fine here.
