### ISSUE TITLE
Why LGPL license?

### ISSUE THREAD

**Issue by and3md** [nomad-software/x11#20]
What are the reasons that X11 dlang package is LGPL? I think that make it unusable in some cases.

**Comment by nomad-software** [comment]
Because this is a fork of existing work that is under the LGPL license. I've no idea why you _think_ that it may be unusable in _some_ cases.

**Comment by and3md** [comment]
I was thinking about use in commercial closed source software. xlib is MIT license so it makes no problems but when it will be used with this d package there will be license problem. Am I wrong?

**Comment by nomad-software** [comment]
So have _you_ had this problem?

**Comment by and3md** [comment]
I'm working on dlangui which is Boost licensed and X11 platform currently has this problem. So I had hoped that maybe you has permission (from original authors) to make this change.

**Comment by nomad-software** [comment]
So why didn't you just ask that to begin with, lol. I'll enquire.

**Comment by and3md** [comment]
> So why didn't you just ask that to begin with, lol.

I'm sorry. I thought that maybe you have your own personal or technical reasons to make it LGPL.

>I'll enquire.

Thanks a lot :) 
That will be fantastic. I think X11 is mostly used by widgets libraries so more free license will make it a lot more usable.

**Comment by nomad-software** [comment]
Asked: http://forum.dlang.org/post/qaqhcpzphywgikdatyyi@forum.dlang.org

**Comment by nomad-software** [comment]
I don't think this is going to be possible. The only solution I can see is for someone else (not connected to this fork or the original repo) to create bindings under a different license and use those.

**Comment by BBasile** [comment]
That's absurd. Everything will be identical.

**Comment by nomad-software** [comment]
Yeah I agree, but easier than getting permission from all contributors and more important, legal.

**Comment by BBasile** [comment]
I'll eventually do it since i use your bindings w/ static linking.

**Comment by BBasile** [comment]
Why not send ping to everybody and send emails...we'll see.

**Comment by BBasile** [comment]
@nomad-software
@weltensturm
@Geod24
@MartinNowak
@BBasile : agreed
@rikkimax

Additionally, contributors to Deimos/libX11

@growlercab
@bioinfornatics
@skilion
@CyberShadow
@Faianca
@Flamaros
@PhilipWitte
@edmccard
@arukuka
@IanWizard
@WalterBright

**Comment by skilion** [comment]
I grant my permission to @nomad-software for changing the license of my past contributions to whatever he thinks is more suitable.

**Comment by weltensturm** [comment]
+

**Comment by BBasile** [comment]
@weltensturm can you be more clear ? Would you agree if the bindings are relicensed to BSL ?

**Comment by weltensturm** [comment]
Oh right, my plus became a dot. I'm fine with Boost/MIT-compatibles. Is the percentage required based on the CLOC contributed?

**Comment by and3md** [comment]
I found that  @bioinfornatics make initial release commit (https://github.com/D-Programming-Deimos/libX11/commit/d6829a7a36e73836b6c50516cb1a4b7540be96c7) and add LGPL license (https://github.com/D-Programming-Deimos/libX11/commit/58c2706b14dbb836bcd4909ff15653a123307b5d). I send mail to him some time ago but no response yet.

**Comment by BBasile** [comment]
@weltensturm: the story of percentage is much more simple: 17 contributors ~ 6 % per contributor. Actually i've read somewhere else that authors of trivial contributions can be ignored. Unfortunately i cannot find any document that states this clearly (for example in Miscrosoft public repos, they evaluate if the authors of a PR need to agree the CLUA to avoid licensing issues. For small PRs this is never the case)

Also this vote is a personal initiative. I'm not the repo owner. It's just that i believe that changing the current license is possible is possible.

**Comment by and3md** [comment]
I just get message from Jonathan Mercier (@bioinfornatics) and we have permission from him to replace the license to one less restrictive :)

**Comment by and3md** [comment]
@BBasile there is one person need to be added to list: @Aatch for example see commit: https://github.com/D-Programming-Deimos/libX11/commit/c19d8cf4b9f0eb72896934246d8c3352861c44f7.

**Comment by Faianca** [comment]
I don't see any problem there. You guys can change what fits the project
better.

**Comment by nomad-software** [comment]
Ok, let's see if we can get permission. 👍

**Comment by BBasile** [comment]
Thanks. I think that on new answers you can [edit the message](https://github.com/nomad-software/x11/issues/20#issuecomment-328518744) where the status is maintained (and put your position too)

**Comment by CyberShadow** [comment]
Some of my commits were changes I submitted on behalf of Ketmar ([example](https://github.com/D-Programming-Deimos/libX11/pull/36)), so you will probably need to get his permission separately.

IIRC, my own changes were mostly superficial; either way, I consent to changing the license to Boost or whatever the license of the original C bindings is.

**Comment by BBasile** [comment]
I've got him on IRC:

> [20:59] ‎<‎B4S1L3‎>‎ You're involved here https://github.com/nomad-software/x11/issues/20#issuecomment-328624198
> ‎[21:00] ‎<‎B4S1L3‎>‎ We need to know if you accept that the projects get licensed as boost or MIT, since you have indirectly contributed, w/ Cybershadow.
> ‎[21:00] ‎<‎ketmar‎>‎ i absolutely don't care. i.e. i'm ok with any license change. you can quote me there ;-)
‎[21:01] ‎<‎B4S1L3‎>‎ thnaks ;)

**Comment by nomad-software** [comment]
To be clear, I give my consent (for any changes I've made) to change the license.

**Comment by bioinfornatics** [comment]
That is ok to me 😀

**Comment by WalterBright** [comment]
What license do I need to agree with?

**Comment by BBasile** [comment]
@WalterBright  Boost or MIT

**Comment by WalterBright** [comment]
So I see :-) but I approve again anyway!

**Comment by bioinfornatics** [comment]
To be clear it is ok to change the license from LGPL to another less restrictive. But to my understanding LGPL do not force enterprise to distribute their code to an open license. If I am correct they are at least 2 cases which you must to use an open license : 1/ you modify this library 2/ you use this library and is static linked.
If you develop your own tool /library you are allowed to have the license of your choice.

**Comment by Geod24** [comment]
I also give my consent to switch the license to Boost or MIT.

**Comment by BBasile** [comment]
@nomad-software, i think it's good now, especially since bioinformatics has agreed. He wrote most of the code.

**Comment by rikkimax** [comment]
I also give consent to switch licenses.

**Comment by nomad-software** [comment]
I've updated the library and created a new release. https://github.com/nomad-software/x11/releases/tag/v1.0.17

The dub package should be updated shortly.

**Comment by and3md** [comment]
Many thanks to all those who help resolve this issue :) 

@nomad-software here remains old license: https://github.com/nomad-software/x11/blob/2f877662205ec175ea015bc7d039f82cc4560bd4/package.json#L6

**Comment by nomad-software** [comment]
Updated the dub file too.

**Comment by growlercab** [comment]
I'm also happy for any contribution I have made to Deimos/libX11 to be
released under a Boost or MIT license. And sorry it took so long to reply,
I've been busy and away from D for a while.

Thanks,
Stewart Hore (growlercab)

**Comment by and3md** [comment]
@growlercab  Thanks for message :) @BBasile Can you update your list :)
