### ISSUE TITLE
Ldc does not accept both XCreateWindow

### ISSUE THREAD

**Issue by rikkimax** [nomad-software/x11#6]
LDC - the LLVM D compiler (0.14.0):
  based on DMD v2.065 and LLVM 3.4.2
and
LDC - the LLVM D compiler (0.15.0-beta1):
  based on DMD v2.066.1 and LLVM 3.5.0

Works fine for dmd 2.066.1, dmd 2.065 and gdc-4.8.2.

../../../.dub/packages/x11-1.0.1/source/x11/Xlib.d(1554): Error: Function type does not match previously declared function with the same mangled name: XCreateWindow

**Comment by nomad-software** [comment]
I'm closing this as I guess it worked?
