### ISSUE TITLE
XConfigureRequestEvent type error

### ISSUE THREAD

**Issue by weltensturm** [nomad-software/x11#9]
[source/c/Xlib.h:821](https://github.com/nomad-software/x11/blob/31275b943c5c10c8d7e0aaed21fe4694de66fe25/source/c/Xlib.h#L821) `unsigned long value_mask;`
vs
[source/x11/Xlib.d:709](https://github.com/nomad-software/x11/blob/31275b943c5c10c8d7e0aaed21fe4694de66fe25/source/x11/Xlib.d#L709) `uint  value_mask;`

how on earth, considering `serial` had the same type but got converted correctly

**Comment by nomad-software** [comment]
Fixed: https://github.com/nomad-software/x11/commit/08ed92ceb89ca7cb5a4e9cdeb591b68148dc0ade
